package gowsdl

var serverHeaderTmpl = `
// Code generated by gowsdl DO NOT EDIT.

package {{.}}

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/hooklift/gowsdl/soap"
	{{/*range .Imports*/}}
		{{/*.*/}}
	{{/*end*/}}
)
`
